variables:
  SRC: "/var/www/contenttrustlab/src"
  SRC_RM: "/var/www/contenttrustlab/src/*"
  DBKEY_SCRIPT: "/var/www/contenttrustlab/dbkey.sh"

build:
  stage: build
  tags:
  - trustlab
  script:
  - . $DBKEY_SCRIPT
  - sudo /bin/systemctl stop gunicorn@contenttrustlab.service
  - sudo chown -R gitlab-runner:www-gitlab $SRC
  - /bin/rm -rf $SRC_RM
  - /bin/cp -arf ./* $SRC
  - cd $SRC
  - mkdir -p deploy/contentrustlab/static
  - sed -i -E "s/('NAME'..')trustlab-dev'/\1trustlab'/" djtrustlab/settings.py
  - sed -i -E "s/('USER'..').*'/\1trustlab'/" djtrustlab/settings.py
  - sed -i -E "s/('PASSWORD'..').*'/\1"$PRODUCTION_DBKEY"'/" djtrustlab/settings.py
  - sed -i "s#STATIC_ROOT = '.*'#STATIC_ROOT = 'deploy/contentrustlab/static'#" djtrustlab/settings.py
  - source ../trustlab-env/bin/activate
  - pip install -r requirements.pip --exists-action w
  - python manage.py migrate
  - python manage.py collectstatic --noinput
  - deactivate
  - sudo chown -R www-data:www-data ./
  - sudo /bin/systemctl start gunicorn@contenttrustlab.service
  - sudo /bin/systemctl restart nginx
  only:
    - develop