NAME = 'TRAVOS DEMO Scenario'

DESCRIPTION = 'TRAVOS DEMO Scenario with 10 agents and 10 observations'

AGENTS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

OBSERVATIONS = [{'authors': ['A'],
                 'before': [0],
                 'details': {'content_trust.topics': ['Web Engineering'],
                             'uri': 'http://example.com/Semantic_Web'},
                 'message': 'Semantic Web',
                 'observation_id': 1,
                 'receiver': 'D',
                 'sender': 'C'},
                {'authors': ['D', 'G', 'B', 'J', 'I'],
                 'before': [1],
                 'details': {'content_trust.topics': ['Web Engineering'],
                             'uri': 'http://example.com/Semantic_Web'},
                 'message': 'Semantic Web',
                 'observation_id': 2,
                 'receiver': 'I',
                 'sender': 'F'},
                {'authors': ['G', 'A', 'D'],
                 'before': [2],
                  'details': {'content_trust.topics': ['Web Engineering'],
                             'uri': 'http://example.com/Semantic_Web'},
                 'message': 'Semantic Web',
                 'observation_id': 3,
                 'receiver': 'B',
                 'sender': 'D'},
                {'authors': ['D', 'F'],
                 'before': [3],
                 'details': {'content_trust.topics': ['Web Engineering'],
                             'uri': 'http://example.com/Semantic_Web'},
                 'message': 'Semantic Web',
                 'observation_id': 4,
                 'receiver': 'B',
                 'sender': 'D'},
                {'authors': ['J', 'H', 'E', 'A'],
                 'before': [4],
                  'details': {'content_trust.topics': ['Web Engineering'],
                             'uri': 'http://example.com/Semantic_Web'},
                 'message': 'Semantic Web',
                 'observation_id': 5,
                 'receiver': 'B',
                 'sender': 'J'},
                {'authors': ['J', 'E'],
                 'before': [5],
                  'details': {'content_trust.topics': ['Web Engineering'],
                             'uri': 'http://example.com/Semantic_Web'},
                 'message': 'Semantic Web',
                 'observation_id': 6,
                 'receiver': 'B',
                 'sender': 'C'},
                {'authors': ['I'],
                 'before': [6],
                  'details': {'content_trust.topics': ['Web Engineering'],
                             'uri': 'http://example.com/Semantic_Web'},
                 'message': 'Semantic Web',
                 'observation_id': 7,
                 'receiver': 'B',
                 'sender': 'F'},
                {'authors': ['H', 'D', 'I', 'F'],
                 'before': [7],
                  'details': {'content_trust.topics': ['Web Engineering'],
                             'uri': 'http://example.com/Semantic_Web'},
                 'message': 'Semantic Web',
                 'observation_id': 8,
                 'receiver': 'D',
                 'sender': 'G'},
                {'authors': ['E', 'C', 'F', 'B', 'J'],
                 'before': [8],
                 'details': {'content_trust.topics': ['Web Engineering'],
                             'uri': 'http://example.com/Semantic_Web'},
                 'message': 'Semantic Web',
                 'observation_id': 9,
                 'receiver': 'F',
                 'sender': 'C'},
                {'authors': ['D', 'B', 'H', 'C', 'F'],
                 'before': [9],
                  'details': {'content_trust.topics': ['Web Engineering'],
                             'uri': 'http://example.com/Semantic_Web'},
                 'message': 'Semantic Web',
                 'observation_id': 10,
                 'receiver': 'B',
                 'sender': 'G'}]
HISTORY = {'A': [('B', 'http://example.com/Semantic_Web', '(2, 18)'),
                 ('C', 'http://example.com/Semantic_Web', '(2, 18)'),
                 ('D', 'http://example.com/Semantic_Web', '(6, 14)'),
                 ('E', 'http://example.com/Semantic_Web', '(9, 11)'),
                 ('F', 'http://example.com/Semantic_Web', '(4, 16)'),
                 ('G', 'http://example.com/Semantic_Web', '(12, 8)'),
                 ('H', 'http://example.com/Semantic_Web', '(17, 3)'),
                 ('I', 'http://example.com/Semantic_Web', '(1, 19)'),
                 ('J', 'http://example.com/Semantic_Web', '(10, 10)')],
           'B': [('A', 'http://example.com/Semantic_Web', '(15, 5)'),
                 ('C', 'http://example.com/Semantic_Web', '(12, 8)'),
                 ('D', 'http://example.com/Semantic_Web', '(10, 10)'),
                 ('E', 'http://example.com/Semantic_Web', '(3, 17)'),
                 ('F', 'http://example.com/Semantic_Web', '(20, 0)'),
                 ('G', 'http://example.com/Semantic_Web', '(13, 7)'),
                 ('H', 'http://example.com/Semantic_Web', '(16, 4)'),
                 ('I', 'http://example.com/Semantic_Web', '(7, 13)'),
                 ('J', 'http://example.com/Semantic_Web', '(8, 12)')
                 ],
           'C': [('A', 'http://example.com/Semantic_Web', '(0, 20)'),
                 ('B', 'http://example.com/Semantic_Web', '(11, 9)'),
                 ('D', 'http://example.com/Semantic_Web', '(3, 17)'),
                 ('E', 'http://example.com/Semantic_Web', '(19, 1)'),
                 ('F', 'http://example.com/Semantic_Web', '(3, 17)'),
                 ('G', 'http://example.com/Semantic_Web', '(5, 15)'),
                 ('H', 'http://example.com/Semantic_Web', '(13, 7)'),
                 ('I', 'http://example.com/Semantic_Web', '(9, 11)'),
                 ('J', 'http://example.com/Semantic_Web', '(7, 13)')
                 ],
           'D': [('A', 'http://example.com/Semantic_Web', '(19, 1)'),
                 ('B', 'http://example.com/Semantic_Web', '(6, 14)'),
                 ('C', 'http://example.com/Semantic_Web', '(15, 5)'),
                 ('E', 'http://example.com/Semantic_Web', '(17, 3)'),
                 ('F', 'http://example.com/Semantic_Web', '(5, 15)'),
                 ('G', 'http://example.com/Semantic_Web', '(14, 6)'),
                 ('H', 'http://example.com/Semantic_Web', '(11, 9)'),
                 ('I', 'http://example.com/Semantic_Web', '(16, 4)'),
                 ('J', 'http://example.com/Semantic_Web', '(19, 1)')
                 ],
           'E': [('A', 'http://example.com/Semantic_Web', '(10, 10)'),
                 ('B', 'http://example.com/Semantic_Web', '(1, 19)'),
                 ('C', 'http://example.com/Semantic_Web', '(12, 8)'),
                 ('D', 'http://example.com/Semantic_Web', '(17, 3)'),
                 ('F', 'http://example.com/Semantic_Web', '(8, 12)'),
                 ('G', 'http://example.com/Semantic_Web', '(16, 4)'),
                 ('H', 'http://example.com/Semantic_Web', '(19, 1)'),
                 ('I', 'http://example.com/Semantic_Web', '(14, 6)'),
                 ('J', 'http://example.com/Semantic_Web', '(7, 13)')
                 ],
           'F': [('A', 'http://example.com/Semantic_Web', '(15, 5)'),
                 ('B', 'http://example.com/Semantic_Web', '(7, 13)'),
                 ('C', 'http://example.com/Semantic_Web', '(17, 3)'),
                 ('D', 'http://example.com/Semantic_Web', '(14, 6)'),
                 ('E', 'http://example.com/Semantic_Web', '(13, 7)'),
                 ('G', 'http://example.com/Semantic_Web', '(5, 15)'),
                 ('H', 'http://example.com/Semantic_Web', '(1, 19)'),
                 ('I', 'http://example.com/Semantic_Web', '(7, 13)'),
                 ('J', 'http://example.com/Semantic_Web', '(2, 18)')
                 ],
           'G': [('A', 'http://example.com/Semantic_Web', '(15, 5)'),
                 ('B', 'http://example.com/Semantic_Web', '(7, 13)'),
                 ('C', 'http://example.com/Semantic_Web', '(12, 8)'),
                 ('D', 'http://example.com/Semantic_Web', '(9, 11)'),
                 ('E', 'http://example.com/Semantic_Web', '(1, 19)'),
                 ('F', 'http://example.com/Semantic_Web', '(20, 0)'),
                 ('H', 'http://example.com/Semantic_Web', '(13, 7)'),
                 ('I', 'http://example.com/Semantic_Web', '(10, 10)'),
                 ('J', 'http://example.com/Semantic_Web', '(0, 20)')
                 ],
           'H': [('A', 'http://example.com/Semantic_Web', '(4, 16)'),
                 ('B', 'http://example.com/Semantic_Web', '(16, 4)'),
                 ('C', 'http://example.com/Semantic_Web', '(19, 1)'),
                 ('D', 'http://example.com/Semantic_Web', '(12, 8)'),
                 ('E', 'http://example.com/Semantic_Web', '(2, 18)'),
                 ('F', 'http://example.com/Semantic_Web', '(9, 11)'),
                 ('G', 'http://example.com/Semantic_Web', '(19, 1)'),
                 ('I', 'http://example.com/Semantic_Web', '(7, 13)'),
                 ('J', 'http://example.com/Semantic_Web', '(18, 2)')
                 ],
           'I': [('A', 'http://example.com/Semantic_Web', '(10, 10)'),
                 ('B', 'http://example.com/Semantic_Web', '(12, 8)'),
                 ('C', 'http://example.com/Semantic_Web', '(5, 15)'),
                 ('D', 'http://example.com/Semantic_Web', '(16, 4)'),
                 ('E', 'http://example.com/Semantic_Web', '(13, 7)'),
                 ('F', 'http://example.com/Semantic_Web', '(6, 14)'),
                 ('G', 'http://example.com/Semantic_Web', '(15, 5)'),
                 ('H', 'http://example.com/Semantic_Web', '(9, 11)'),
                 ('J', 'http://example.com/Semantic_Web', '(13, 7)')
                 ],
           'J': [('A', 'http://example.com/Semantic_Web', '(17, 3)'),
                 ('B', 'http://example.com/Semantic_Web', '(3, 17)'),
                 ('C', 'http://example.com/Semantic_Web', '(13, 7)'),
                 ('D', 'http://example.com/Semantic_Web', '(15, 5)'),
                 ('E', 'http://example.com/Semantic_Web', '(18, 2)'),
                 ('F', 'http://example.com/Semantic_Web', '(14, 6)'),
                 ('G', 'http://example.com/Semantic_Web', '(8, 12)'),
                 ('H', 'http://example.com/Semantic_Web', '(10, 10)'),
                 ('I', 'http://example.com/Semantic_Web', '(16, 4)')]}

SCALES_PER_AGENT = {'A': {'cooperation': 0.5,
                          'default': 0.0,
                          'forgivability': -0.5,
                          'maximum': 1.0,
                          'minimum': -1.0,
                          'name': 'Trust Scale by Marsh and Briggs (2009)',
                          'package': 'marsh_briggs_scale'},
                    'B': {'cooperation': 0.5,
                          'default': 0.0,
                          'forgivability': -0.5,
                          'maximum': 1.0,
                          'minimum': -1.0,
                          'name': 'Trust Scale by Marsh and Briggs (2009)',
                          'package': 'marsh_briggs_scale'},
                    'C': {'cooperation': 0.5,
                          'default': 0.0,
                          'forgivability': -0.5,
                          'maximum': 1.0,
                          'minimum': -1.0,
                          'name': 'Trust Scale by Marsh and Briggs (2009)',
                          'package': 'marsh_briggs_scale'},
                    'D': {'cooperation': 0.5,
                          'default': 0.0,
                          'forgivability': -0.5,
                          'maximum': 1.0,
                          'minimum': -1.0,
                          'name': 'Trust Scale by Marsh and Briggs (2009)',
                          'package': 'marsh_briggs_scale'},
                    'E': {'cooperation': 0.5,
                          'default': 0.0,
                          'forgivability': -0.5,
                          'maximum': 1.0,
                          'minimum': -1.0,
                          'name': 'Trust Scale by Marsh and Briggs (2009)',
                          'package': 'marsh_briggs_scale'},
                    'F': {'cooperation': 0.5,
                          'default': 0.0,
                          'forgivability': -0.5,
                          'maximum': 1.0,
                          'minimum': -1.0,
                          'name': 'Trust Scale by Marsh and Briggs (2009)',
                          'package': 'marsh_briggs_scale'},
                    'G': {'cooperation': 0.5,
                          'default': 0.0,
                          'forgivability': -0.5,
                          'maximum': 1.0,
                          'minimum': -1.0,
                          'name': 'Trust Scale by Marsh and Briggs (2009)',
                          'package': 'marsh_briggs_scale'},
                    'H': {'cooperation': 0.5,
                          'default': 0.0,
                          'forgivability': -0.5,
                          'maximum': 1.0,
                          'minimum': -1.0,
                          'name': 'Trust Scale by Marsh and Briggs (2009)',
                          'package': 'marsh_briggs_scale'},
                    'I': {'cooperation': 0.5,
                          'default': 0.0,
                          'forgivability': -0.5,
                          'maximum': 1.0,
                          'minimum': -1.0,
                          'name': 'Trust Scale by Marsh and Briggs (2009)',
                          'package': 'marsh_briggs_scale'},
                    'J': {'cooperation': 0.5,
                          'default': 0.0,
                          'forgivability': -0.5,
                          'maximum': 1.0,
                          'minimum': -1.0,
                          'name': 'Trust Scale by Marsh and Briggs (2009)',
                          'package': 'marsh_briggs_scale'}}

METRICS_PER_AGENT = {'A': {'__final__': {'name': 'travos'}, 'travos.experience': {}, 'travos.opinion': {}},
                     'B': {'__final__': {'name': 'travos'}, 'travos.experience': {}, 'travos.opinion': {}},
                     'C': {'__final__': {'name': 'travos'}, 'travos.experience': {}, 'travos.opinion': {}},
                     'D': {'__final__': {'name': 'travos'}, 'travos.experience': {}, 'travos.opinion': {}},
                     'E': {'__final__': {'name': 'travos'}, 'travos.experience': {}, 'travos.opinion': {}},
                     'F': {'__final__': {'name': 'travos'}, 'travos.experience': {}, 'travos.opinion': {}},
                     'G': {'__final__': {'name': 'travos'}, 'travos.experience': {}, 'travos.opinion': {}},
                     'H': {'__final__': {'name': 'travos'}, 'travos.experience': {}, 'travos.opinion': {}},
                     'I': {'__final__': {'name': 'travos'}, 'travos.experience': {}, 'travos.opinion': {}},
                     'J': {'__final__': {'name': 'travos'}, 'travos.experience': {}, 'travos.opinion': {}}}
