NAME = 'Travos Test Scenario Basic'

AGENTS = ['A', 'B', 'C', 'D']

OBSERVATIONS = [{'authors': ['A'],
                 'before': [],
                 'details': {'uri': 'http://example.com/PHP'},
                 'message': 'PHP',
                 'observation_id': 1,
                 'receiver': 'B',
                 'sender': 'A'},
                {'authors': ['A'],
                 'before': [1],
                 'details': {'uri': 'http://example.com/WOT'},
                 'message': 'Web of Things',
                 'observation_id': 2,
                 'receiver': 'B',
                 'sender': 'A'},
                {'authors': ['A'],
                 'before': [2],
                 'details': {'uri': 'http://example.com/Html'},
                 'message': 'HTML',
                 'observation_id': 3,
                 'receiver': 'B',
                 'sender': 'A'},
                {'authors': ['C'],
                 'before': [3],
                 'details': {'uri': 'http://example.com/Css'},
                 'message': 'Semantic Web',
                 'observation_id': 4,
                 'receiver': 'B',
                 'sender': 'C'},
                {'authors': ['C'],
                 'before': [4],
                 'details': {'uri': 'http://example.com/Solid'},
                 'message': 'Solid',
                 'observation_id': 5,
                 'receiver': 'B',
                 'sender': 'C'},
                {'authors': ['C'],
                 'before': [5],
                 'details': {'uri': 'http://example.com/IOT'},
                 'message': 'Internet of Things',
                 'observation_id': 6,
                 'receiver': 'B',
                 'sender': 'C'}
                ]

HISTORY = {'A': [['B', 'http://example.com/Semantic_Web', '(9, 14)'],
                 ['C', 'http://example.com/Web-based_learning', '(18, 11)'],
                 ['D', 'http://example.com/Semantic_Web', '(2, 15)']],
           'B': [['A', 'http://example.com/Semantic_Web', '(17, 5)'],
                 ['C', 'http://example.com/Web-based_learning', '(3, 0)'],
                 ['D', 'http://example.com/Web_Assembly', '(18, 5)']],
           'C': [['A', 'http://example.com/Linked_Data', '(4, 1)'],
                 ['B', 'http://example.com/Web-based_learning', '(3, 1)'],
                 ['D', 'http://example.com/Web_of_Things', '(7, 3)']],
           'D': [['A', 'http://example.com/Web_Assembly', '(3, 0)'],
                 ['B', 'http://example.com/Linked_Data', '(6, 2)'],
                 ['C', 'http://example.com/Web_Assembly', '(15, 46)']]}



SCALES_PER_AGENT = {'A': {'cooperation': 0.5,
                          'default': 0.0,
                          'forgivability': -0.5,
                          'maximum': 1.0,
                          'minimum': -1.0,
                          'name': 'Trust Scale by Marsh and Briggs (2009)',
                          'package': 'marsh_briggs_scale'},
                    'B': {'cooperation': 0.5,
                          'default': 0.0,
                          'forgivability': -0.5,
                          'maximum': 1.0,
                          'minimum': -1.0,
                          'name': 'Trust Scale by Marsh and Briggs (2009)',
                          'package': 'marsh_briggs_scale'},
                    'C': {'cooperation': 0.5,
                          'default': 0.0,
                          'forgivability': -0.5,
                          'maximum': 1.0,
                          'minimum': -1.0,
                          'name': 'Trust Scale by Marsh and Briggs (2009)',
                          'package': 'marsh_briggs_scale'},
                    'D': {'cooperation': 0.5,
                          'default': 0.0,
                          'forgivability': -0.5,
                          'maximum': 1.0,
                          'minimum': -1.0,
                          'name': 'Trust Scale by Marsh and Briggs (2009)',
                          'package': 'marsh_briggs_scale'}}

METRICS_PER_AGENT = {'A': {'__final__': {'name': 'travos'},
                           'travos.experience': {},
                           'travos.opinion': {}},
                     'B': {'__final__': {'name': 'travos'},
                           'travos.experience': {},
                           'travos.opinion': {}},
                     'C': {'__final__': {'name': 'travos'},
                           'travos.experience': {},
                           'travos.opinion': {}},
                     'D': {'__final__': {'name': 'travos'},
                           'travos.experience': {},
                           'travos.opinion': {}}}

DESCRIPTION = 'This is a basic travos scenario with four agents.'
